### ISSUE TITLE
image size, two-step dockerfile build

### ISSUE THREAD

**Issue by j-forster** [Waziup/wazigate-system#1]
Ref: https://github.com/Waziup/waziup-gateway/issues/15

> waziup/wazigate-system | V1.0-beta1 | ae5756e517e4 | 5 weeks ago | 908MB

The image size of the waziup-system image is huge compared to other images from wazigate.
Maybe we can reduce this size if the [Dockerfile](https://github.com/Waziup/wazigate-system/blob/master/Dockerfile) get a two-step build using only a compiled executable for the build images (together with all the required tools)?

**Comment by cdupont** [comment]
Would be nice to have a break-down of the size

**Comment by cdupont** [comment]
Done: https://github.com/Waziup/wazigate-system/commit/3bef6c29c768bc1d844f4d3948e585c8f1f5f219
wazigate-system image size is now 170Mo
